package models

var EventosCoban = map[string]string{
	"001":              "Por Tiempo",
	"sharp turn alarm": "Giro brusco",
	"accelerate alarm": "Acelaracion Brusca",
	"help me":          "Alarma SOS",
	"low battery":      "Batería baja",
	"move":             "Vehiculo en Movimiento",
	"speed":            "Alarma por velocidad",
	"stockade":         "GEO-cerca",
	"ac alarm":         "Alarma de apagado",
	"acc on":           "Vehiculo encendido",
	"acc off":          "Vehiculo apagado",
	"door alarm":       "Puerta abierta",
	"sensor alarm":     "Choque",
	"acc alarm":        "accesorio",
	"accident alarm":   "Accidente",
	"bonnet alarm":     "Capó",
	"footbrake alarm":  "Freno de pie",
	"T":                "Temperatura",
	"oil":              "Combustible",
	"collision alarm":  "Colisión",
	"DTC P0001":        "Código de problema de diagnóstico: P0001",
	"service":          "Notificación de mantenimiento del vehículo",
}
